services:
  db:
    image: mysql:8.0
    container_name: match-live-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5

  backend:
    build: .
    container_name: match-live-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: match-live-db
      DB_PORT: 3306
      DB_USER: nestjs
      DB_PASSWORD: nestjspassword
      DB_NAME: meczomat
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:prod
    ports:
      - '3000:3000'

volumes:
  db_data: